WebMVC/Controllers/AdminCategoryController.cs
using BusinessLayer.Concrete;
using BusinessLayer.ValidationRules;
using DataAccsesLayer.Concrete.Repositories;
using DataAccsesLayer.EntityFramework;
using EntityLayer.Concrete;
using FluentValidation.Results;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebMVC.Controllers
{
    public class AdminCategoryController : Controller
    {
        CategoryManager cm = new CategoryManager(new EfCategoryDal());

        public ActionResult Index()
        {
            var categoryvalues = cm.GetList();
            return View("~/Views/AdminCategory/Index.cshtml", categoryvalues);
        }



        #region ActionResult to !!!  Add  !!! Category

        [HttpGet]
        public ActionResult AddCategory()
        {
            return View();
        }

        [HttpPost]
        public ActionResult AddCategory(Category p)
        {
            CategoryValidator categoryValidator = new CategoryValidator();
            ValidationResult results = categoryValidator.Validate(p);
            if (results.IsValid)
            {
                cm.CategoryAdd(p);
                return RedirectToAction("Index");
            }
            else
            {
                foreach (var item in results.Errors)
                {
                    ModelState.AddModelError(item.PropertyName, item.ErrorMessage);
                }
            }
            return View();
        }

        #endregion

        #region ActionResult to !!!  Delete  !!! Category

        public ActionResult DeleteCategory(int id)
        {
            var catergoryvalue = cm.GetById(id);
            cm.CategoryDelete(catergoryvalue);
            return RedirectToAction("Index");
        }

        #endregion

        #region ActionResult to !!!  EDIT  !!! Category

        [HttpGet]
        public ActionResult EditCategory(int id)
        {
            var categoryvalue = cm.GetById(id);
            return View(categoryvalue);
        }
        [HttpPost]
        public ActionResult EditCategory(Category p)
        {
            cm.CategoryUpdate(p);
            return RedirectToAction("Index");
        }

        #endregion
    }
}

WebMVC/Views/AdminCategory/AddCategory.cshtml
@model EntityLayer.Concrete.Category

@{
    ViewBag.Title = "AddCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}


<h3 style="text-align:center;">Kategori Ekleme Sayfası</h3>
<br />

@using (Html.BeginForm("AddCategory", "AdminCategory", FormMethod.Post))
{
    <div class="form-group">
        @Html.Label("Kategori Adı")
        @Html.TextBoxFor(x => x.CategoryName, new{ @class = "form-control"})
        @Html.ValidationMessageFor(x => x.CategoryName)
        <br />
        <br />
        @Html.Label("Kategori Açıklama")
        @Html.TextAreaFor(x => x.CategoryDescription, new { @class = "form-control" })
        @Html.ValidationMessageFor(x => x.CategoryDescription)
        <br />
        <br />
        <button class="btn-danger">Kategoriyi Ekle</button>
    </div>
}

WebMVC/Views/AdminCategory/EditCategory.cshtml
@model EntityLayer.Concrete.Category

@{
    ViewBag.Title = "EditCategory";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}
<br />
<br />

<h2 style="text-align:center;">Kategori Güncelleme Sayfası</h2>

@using (Html.BeginForm("EditCategory", "AdminCategory", FormMethod.Post))
{
<div class="form-horizontal">
    @Html.Label("Kategori ID:")
    @Html.TextBoxFor(x => x.CategoryID, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CategoryID)
    <br />
    <br />
    @Html.Label("Kategori Adı:")
    @Html.TextBoxFor(x => x.CategoryName, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CategoryName)
    <br />
    <br />
    @Html.Label("Kategori Açıklama:")
    @Html.TextAreaFor(x => x.CategoryDescription, new { @class = "form-control" })
    @Html.ValidationMessageFor(x => x.CategoryDescription)
    <br />
    <br />
    <button class="btn-danger">GÜNCELLE</button>
</div>
}

WebMVC/Views/AdminCategory/Index.cshtml
@using EntityLayer.Concrete
@model List<Category>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_AdminLayout.cshtml";
}

<br /><br />
<table class="table table-bordered">
    <tr>
        <th>#</th>
        <th>Kategori Adı</th>
        <th>Kategori Açıklaması</th>
        <th>Sil</th>
        <th>Güncelle</th>
        <th>Başlıklar</th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <th>@item.CategoryID</th>
            <td>@item.CategoryName</td>
            <td>@item.CategoryDescription</td>
            <th><a href="/AdminCategory/DeleteCategory/@item.CategoryID" class="btn btn-danger">Sil</a></th>
            <th><a href="/AdminCategory/EditCategory/@item.CategoryID" class="btn btn-warning">Güncelle</a></th>
            <th><a href="#" class="btn btn-primary">Başlıklar</a></th>
        </tr>
    }
</table>
<a href="/AdminCategory/AddCategory" class="btn btn-danger">Yeni Kategori</a>